---
output: 
  html_document: 
    theme: cerulean
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
options(width=120)

library(plyr)
library(rgdal)
library(knitr)
library(maptools)

library(ProjectTemplate)
setwd('..')
load.project()

# Read in some additional vector data. NOTE that these shapefiles are vectorized
# from the raster files used in the analysis and therefore can slightly 
# differ from the original vector files.
data_dir <- "/home/jlehtoma/GitHub/zsetup-esmk/data/common/vector"
pa_vector <- readShapePoly(file.path(data_dir, "esmk_pas_nopeat.shp"))
wkh_vector <- readShapePoly(file.path(data_dir, "esmk_wkh.shp"))
metso_vector <- readShapePoly(file.path(data_dir, "esmk_metso.shp"))

```

### Fraction of the landscape covered by various data sources

Reading from the actual data sources, fractions of the whole landscape covered 
by different data sources are the following:

```{r fractions-data, echo=FALSE, results='asis'}
tot.cov <- table(getValues(ds.mask))

covs <- data.frame("Dataset"=c("Detailed (NHS)", "Detailed (FFC)", 
                               "Coarse (FRI)"),
                   "Code"=names(tot.cov),
                   "Cells"=as.vector(tot.cov),
                   "Percent"=round(as.vector(tot.cov) / sum(tot.cov) * 100, 2))
kable(covs)

```

### Fraction of the landscape covered by various validation data sets

```{r fractions-val-data, echo=FALSE, results='asis'}

val.cells <- c(sum(!is.na(getValues(pa.mask))),
               sum(!is.na(getValues(wkh.mask))),
               sum(!is.na(getValues(metso.mask))))

val.covs <- data.frame("Dataset" = c("PAs", "WKH", "METSO"),
                       "Cells" = val.cells,
                       "Fraction" = round(val.cells / sum(tot.cov) * 100, 2),
                       "Mean_poly_area_ha" = round(c(mean(pa_vector$area_ha),
                                                     mean(wkh_vector$area_ha),
                                                     mean(metso_vector$area_ha)), 
                                                   2))
kable(val.covs)

```
